import {
  Apple,
  Armchair,
  Bed,
  BookOpen,
  Camera,
  Coffee,
  Drill,
  Footprints,
  Hammer,
  Headphones,
  Laptop,
  Microwave,
  Mouse,
  Pencil,
  Refrigerator,
  Shirt,
  Smartphone,
  Sofa,
  Tablet,
  ToyBrick,
  WashingMachine,
  Wrench,
} from "lucide-react";

export const icons = [
  { id: 1, icon: <BookOpen />, isSelected: true },
  { id: 2, icon: <Laptop />, isSelected: false },
  { id: 3, icon: <Smartphone />, isSelected: false },
  { id: 4, icon: <Tablet />, isSelected: false },
  { id: 5, icon: <Shirt />, isSelected: false },
  { id: 6, icon: <Pencil />, isSelected: false },
  { id: 7, icon: <Camera />, isSelected: false },
  { id: 8, icon: <Headphones />, isSelected: false },
  { id: 9, icon: <Apple />, isSelected: false },
  { id: 10, icon: <Sofa />, isSelected: false },
  { id: 11, icon: <Armchair />, isSelected: false },
  { id: 12, icon: <Footprints />, isSelected: false },
  { id: 13, icon: <Wrench />, isSelected: false },
  { id: 14, icon: <Hammer />, isSelected: false },
  { id: 15, icon: <WashingMachine />, isSelected: false },
  { id: 16, icon: <Microwave />, isSelected: false },
  { id: 17, icon: <ToyBrick />, isSelected: false },
  { id: 18, icon: <Drill />, isSelected: false },
  { id: 19, icon: <Mouse />, isSelected: false },
  { id: 20, icon: <Bed />, isSelected: false },
  { id: 21, icon: <Refrigerator />, isSelected: false },
  { id: 22, icon: <Coffee />, isSelected: false },
];
