import { nanoid } from "nanoid";
import { Product } from "./columns";
import {
  Bed,
  Drill,
  Hammer,
  LampDesk,
  Laptop,
  Microwave,
  Mouse,
  Refrigerator,
  Smartphone,
  ToyBrick,
  WashingMachine,
  Wrench,
} from "lucide-react";

export const products: Product[] = [
  {
    id: nanoid(),
    name: "Screwdriver",
    supplier: "ToolSupplier Inc.",
    sku: "SD123",
    category: "Others",
    status: "Draft",
    quantityInStock: 50,
    price: 12.99,
    icon: <Wrench />,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: nanoid(),
    name: "Hammer",
    supplier: "ToolSupplier Inc.",
    sku: "HM456",
    category: "Others",
    status: "Published",
    quantityInStock: 30,
    price: 15.99,
    icon: <Hammer />,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: nanoid(),
    name: "Smartphone",
    supplier: "TechWorld",
    sku: "SP789",
    category: "Electronics",
    status: "Published",
    quantityInStock: 100,
    price: 599.0,
    icon: <Smartphone />,
    createdAt: new Date("2023-12-03"),
  },
  {
    id: nanoid(),
    name: "Laptop",
    supplier: "TechWorld",
    sku: "LT101",
    category: "Electronics",
    status: "Inactive",
    quantityInStock: 25,
    price: 899.0,
    icon: <Laptop />,
    createdAt: new Date("2023-06-25"),
  },
  {
    id: nanoid(),
    name: "Microwave Oven",
    supplier: "HomeGoods Co.",
    sku: "MO202",
    category: "Electronics",
    status: "Draft",
    quantityInStock: 12,
    price: 120.0,
    icon: <Microwave />,
    createdAt: new Date("2024-03-05"),
  },
  {
    id: nanoid(),
    name: "Washing Machine",
    supplier: "HomeGoods Co.",
    sku: "WM303",
    category: "Electronics",
    status: "Published",
    quantityInStock: 9,
    price: 499.0,
    icon: <WashingMachine />,
    createdAt: new Date("2024-11-19"),
  },
  {
    id: nanoid(),
    name: "Outdoor Furniture Set",
    supplier: "FurnitureGalore",
    sku: "OF812",
    category: "Furniture",
    status: "Published",
    quantityInStock: 12,
    price: 799.99,
    icon: <Bed />,
    createdAt: new Date("2024-08-11"),
  },
  {
    id: nanoid(),
    name: "Gaming Mouse",
    supplier: "TechWorld",
    sku: "GM904",
    category: "Electronics",
    status: "Published",
    quantityInStock: 55,
    price: 59.99,
    icon: <Mouse />,
    createdAt: new Date("2023-12-01"),
  },
  {
    id: nanoid(),
    name: "Desk Lamp",
    supplier: "HomeGoods Co.",
    sku: "DL803",
    category: "Electronics",
    status: "Draft",
    quantityInStock: 30,
    price: 34.99,
    icon: <LampDesk />,
    createdAt: new Date("2023-11-05"),
  },
  {
    id: nanoid(),
    name: "Refrigerator",
    supplier: "HomeGoods Co.",
    sku: "RF404",
    category: "Furniture",
    status: "Inactive",
    quantityInStock: 8,
    price: 799.99,
    icon: <Refrigerator />,
    createdAt: new Date("2023-07-10"),
  },
  {
    id: nanoid(),
    name: "Cordless Drill",
    supplier: "ToolSupplier Inc.",
    sku: "CD307",
    category: "Others",
    status: "Inactive",
    quantityInStock: 35,
    price: 99.99,
    icon: <Drill />,
    createdAt: new Date("2024-03-22"),
  },
  {
    id: nanoid(),
    name: "Toy Bricks",
    supplier: "Playful Wonders Co.",
    sku: "TB709",
    category: "Toys",
    status: "Published",
    quantityInStock: 28,
    price: 89.99,
    icon: <ToyBrick />,
    createdAt: new Date("2024-05-18"),
  },
];
